### ISSUE TITLE
PROJ-009: FE Signup

### ISSUE THREAD

**Issue by SeanEngineering** [Revenology/traveler-expo-app#5]
Requirements:
- Needs to check db if user exists
- Need to check user password is at least 8 letters long, a number and special character
- Needs to be a valid email

- Be able to signup with Google services, facebook, ...

**Comment by SeanEngineering** [comment]
Basic fields completed, UI needs to be improved

**Comment by SeanEngineering** [comment]
TODO: Implement checks. They have been added in the utils folder.

**Comment by GubbyDuo** [comment]
Still need to edit this one to finish PROJ-009, should we move it back to In Progress? @SeanEngineering

**Comment by SeanEngineering** [comment]
I think split this one in the todo section to be picked up later by anyone if they want @GubbyDuo
